---
title: "National priorities for Angola"
author: "*Compiled on `r date()` by `r Sys.info()['user']`*"
output: 
  html_document:
    code_folding: show
    toc: true
    toc_depth: 1
    toc_float: yes
    number_sections: false
    theme: cerulean
    highlight: haddock
---

```{r}
library(raster)
library(sf)
library(tidyverse)

knitr::opts_chunk$set(echo = F, message = F, warning = F,  prompt = F, comment = F)

options(scipen = 999)
```

```{r}
country_name <- "Angola"

country_iso3c <- countrycode::countrycode(country_name, origin = "country.name", destination = "iso3c")

local_crs <- "+proj=aea +lat_1=20 +lat_2=-23 +lat_0=0 +lon_0=25 +x_0=0 +y_0=0 +ellps=WGS84 +datum=WGS84 +units=m +no_defs"

dir.create(country_name)
```

# Load data

```{r}
source("01_setup.R")
```

## EEZ & land

```{r}
eez <- world_eezs %>% 
  filter(pol_type %in% c("Union EEZ and country")) %>% 
  filter(territory1 %in% country_name) %>% 
  st_transform(crs = crs(ocean_low_res_moll)) 

eez_raster <- eez %>% 
  rasterize(ocean_low_res_moll, field = 1) %>% 
  mask(ocean_low_res_moll)
```

```{r}
land_shp <- rnaturalearth::ne_countries(scale = 50,country = country_name, returnclass = "sf")
```

```{r}
highly_mpas <- highly_mpas %>% 
  filter(country == country_iso3c)
```

## Ocean df

```{r}
eez_df <- stack(ocean_low_res_moll, eez_raster) %>% 
  raster::as.data.frame(xy = T) %>% 
  set_names(c("lon", "lat", "ocean","f_eez")) %>% 
  filter(!is.na(ocean)) %>% 
  rowid_to_column(var = "cell_id") %>% 
  as_tibble() %>% 
  filter(!is.na(f_eez))

ocean_df <- ocean_df %>% 
  left_join(eez_df)

(protection_levels <- ocean_df %>% 
  summarise(f_highly_mpas = sum(f_highly_mpa/n()),
            eez_size = sum(f_eez, na.rm = T),
            f_eez_highly_mpas = sum(f_highly_mpa[f_eez > 0]/eez_size, na.rm = T)) %>% 
  mutate_if(is.numeric, round, 4) )

eez_cell_ids <- ocean_df$cell_id[ocean_df$f_eez > 0]
```

## Local carbon

```{r}
carbon_hr <- raster(file.path(gocp_project_dir, "data", "02_processed", "impacts", "bottom_trawling", "carbon_hr.tif")) # Mg C km^2

co2_efflux <- raster(file.path(gocp_project_dir, "data", "02_processed", "impacts", "bottom_trawling", "co2_efflux.tif")) # Mg C km^2

hr_cell_area <- 934.4789^2/1000000

eez_co2 <- co2_efflux %>% 
  crop(as_Spatial(eez)) %>% 
  mask(as_Spatial(eez))

total_co2_in_eez <- cellStats(eez_co2, sum)*hr_cell_area

total_co2_in_eez/10^6

eez_carbon <- carbon_hr %>% 
  crop(as_Spatial(eez)) %>% 
  mask(as_Spatial(eez))

total_carbon_in_eez <- cellStats(eez_carbon, sum)*hr_cell_area

total_carbon_in_eez/10^6
```

# Ranking

## Adjust K, make NA outside EEZ, and normalize

```{r}
eez_rows <- rownames(norm_features_matrix) %in% eez_cell_ids

fraction_k_in_eez <- colSums(norm_features_matrix[eez_rows, stock_names, drop = F], na.rm = T)

stocks_info$k <- stocks_info$k*fraction_k_in_eez[stock_names]
```


```{r}
norm_features_matrix[!eez_rows, stock_names] <- NA

norm_features_matrix[, stock_names] <- sweep(norm_features_matrix[, stock_names], 2, colSums(norm_features_matrix[, stock_names], na.rm = T), FUN = "/")

norm_features_matrix[is.na(norm_features_matrix)] <- 0

sum(colSums(norm_features_matrix[, stock_names]))
```

## Initial conditions

```{r}
z_bio <-  0.25

is_mpa_vect <- ocean_df$f_highly_mpa > 0

protected_cells <- matrix(is_mpa_vect, nrow = 1, ncol = nrow(norm_features_matrix))

unprotected_matrix <- norm_features_matrix[!protected_cells, ]

protected_matrix <- norm_features_matrix[protected_cells, ]

baseline_state <- protected_cells%*%norm_features_matrix

baseline_state[,"carbon"] <- baseline_state[, "carbon"] + carbon_remains_BAU

baseline_state[, bio_feature_names] <- baseline_state[, bio_feature_names] + bio_remains_BAU

max_slopes_bio <- z_bio*baseline_state[, bio_feature_names]^(z_bio - 1)

max_slope_carbon <- 1

names(max_slope_carbon) <- "carbon"
```

## Limiting ranking to ROI

```{r}
unprotected_matrix <- unprotected_matrix[rownames(unprotected_matrix) %in% eez_cell_ids,] ## Algorithm can only choose from within EEZ. 
```

## Run algorithm

```{r}
calculate_multiobjective_weights <- function(alpha_b, alpha_c, alpha_f, 
                                             b_wts, c_wts, f_wts, 
                                             max_b, max_c, max_f_a1, max_f_a2, 
                                             effort_assumption){
  
  if(all(c(alpha_b, alpha_c, alpha_f) >= 0) & alpha_b + alpha_c + alpha_f != 1) stop("weights don't add up to 1")
  
  if(effort_assumption == 1){
    max_f <- max_f_a1
  } 
  else if (effort_assumption == 2){
    max_f <- max_f_a2
  }
  
  bio_w <- alpha_b*b_wts*max_f/max_b
  
  carbon_w <- alpha_c*c_wts*max_f/max_c
  
  food_w <- alpha_f*f_wts
  
  feature_weigths <- c(bio_w, carbon_w, food_w)
  
  return(feature_weigths)
  
}
```

```{r}
estimate_multiobjective_slopes <- function(x, feature_group, feature_wts, max_slopes_b, max_slopes_c,
                                           z_bio = 0.25, z_carbon = 1, effort_assumption,  e, m, k, r){

  slopes <- vector(mode = "numeric", length = length(feature_group))

  slopes[feature_group == 1] <- pmin(max_slopes_b, z_bio*x[feature_group == 1]^(z_bio - 1))

  slopes[feature_group == 2] <- pmin(max_slopes_c, z_carbon*x[feature_group == 2]^(z_carbon - 1))

  slopes[feature_group == 3] <- estimate_catch_slopes(k_protected = x[feature_group == 3],
                                                      effort_assumption = effort_assumption,
                                                      e = e,
                                                      m = m,
                                                      k = k,
                                                      r = r)

  weighted_slopes <- slopes*feature_wts

  return(weighted_slopes)

}
```

```{r}
run_prioritization <- function(unprotected_matrix, wts, step_size){
  
  ranking <- list()
  
  current_pick <- 0
  
  current_state <- baseline_state
  
  while(nrow(unprotected_matrix) > 0){
    
    current_pick <- sum(current_pick, 1)
    
    slopes <- estimate_multiobjective_slopes(x = current_state, feature_group = group_ids, feature_wts  = wts,
                                             max_slopes_b = max_slopes_bio, max_slopes_c = max_slope_carbon, 
                                             e = stocks_info$ex_rate, m = stocks_info$m, k = stocks_info$k, 
                                             r = stocks_info$r, effort_assumption = 2)
    
    delta <- unprotected_matrix%*%as.matrix(slopes)
    
    best_cell_indeces <- doBy::which.maxn(delta, n = step_size)
    
    best_cells <- delta[best_cell_indeces,] %>%
      enframe() %>%
      set_names(c('cell_id', "delta")) %>%
      mutate(pick_order = current_pick)
    
    ranking <- bind_rows(ranking, best_cells)
    
    current_state <- unprotected_matrix[best_cell_indeces, ,drop = F] %>%
      colSums() +
      current_state
    
    unprotected_matrix <- unprotected_matrix[-best_cell_indeces, , drop = F]
  }
  
  ranking$cell_id <- as.integer(ranking$cell_id)
  
  return(ranking)
  
}
```

```{r}
food_ranking <- run_prioritization(unprotected_matrix, 
                                   step_size = 1,
                                   wts = calculate_multiobjective_weights(alpha_b = 0, alpha_c = 0, alpha_f = 1,
                                                                          b_wts = bio_weights, c_wts = carbon_weights,
                                                                          f_wts = food_weights, max_b = 1, max_c = 1, 
                                                                          max_f_a1  = 1, max_f_a2  = 1, effort_assumption = 2))

bio_ranking <- run_prioritization(unprotected_matrix, 
                                   step_size = 1,
                                   wts = calculate_multiobjective_weights(alpha_b = 1, alpha_c = 0, alpha_f = 0,
                                                                          b_wts = bio_weights, c_wts = carbon_weights,
                                                                          f_wts = food_weights, max_b = 1, max_c = 1, 
                                                                          max_f_a1  = 1, max_f_a2  = 1, effort_assumption = 2))

carbon_ranking <- run_prioritization(unprotected_matrix, 
                                   step_size = 1,
                                   wts = calculate_multiobjective_weights(alpha_b = 0, alpha_c = 1, alpha_f = 0,
                                                                          b_wts = bio_weights, c_wts = carbon_weights,
                                                                          f_wts = food_weights, max_b = 1, max_c = 1, 
                                                                          max_f_a1  = 1, max_f_a2  = 1, effort_assumption = 2))
```

# Results

## Bio

```{r}
norm_features_df <- norm_features_matrix %>%
  as_tibble(rownames = NA) %>%
  rownames_to_column("cell_id") 

norm_features_df$cell_id <- as.integer(norm_features_df$cell_id)
```

```{r}
bio_benefit_curve <- get_benefit_curve(goal = "biodiversity", rank_df = bio_ranking)

plot_curve(curve_df = bio_benefit_curve, 
           goal = "biodiversity",
           country_name = country_name)+
  theme(plot.title.position = "plot")+
  ggsave(filename = file.path(country_name, "bio_curve.png"), height = 5, width = 7)

(max_bio_delta <- bio_benefit_curve %>% 
  summarize(max_v = max(v),
            current_mpas_v = if_else(protection_levels$f_eez_highly_mpas <= 0, 0, 
                                     max(v[fraction_protected <= protection_levels$f_eez_highly_mpas])),
            max_delta_v = max_v - current_mpas_v,
            ninety_percent_delta_v = current_mpas_v + 0.9*max_delta_v,
            optim_protection = 100*max(fraction_protected[v == max_v]),
            optim_protection_90 = 100*max(fraction_protected[which.min(abs(ninety_percent_delta_v - v))])) %>% 
   mutate_at(vars(optim_protection_90, optim_protection), round, 2))
```


```{r, warning = F}
bio_raster <- bio_ranking %>% 
  rasterize_ranking() 

map_priorities(rank_raster = bio_raster, 
               priority = "biodiversity", 
               scenario = country_name,
               projection = local_crs, 
               mpas_shp = highly_mpas,
               land_shp = land_shp) +
    ggsave(filename = file.path(country_name, "bio_map.png"), height = 7, width = 7)
```

```{r}
bio_summary <- bio_benefit_curve %>% 
  mutate(v = scales::rescale(v)) %>% 
  summarize(objective = "biodiversity",
            max_v = max(v),
            optim_protection = fraction_protected[v == max_v],
            v_at_10_percent = v[which.min(abs(fraction_protected - 0.1))],
            v_at_30_percent = v[which.min(abs(fraction_protected - 0.3))])
```
## Carbon

```{r}
carbon_benefit_curve <- get_benefit_curve(goal = "carbon", rank_df = carbon_ranking)

plot_curve(curve_df = carbon_benefit_curve, goal = "carbon", country_name = country_name)+
  theme(plot.title.position = "plot")+
  ggsave(filename = file.path(country_name, "carbon_curve.png"), height = 5, width = 7)

(max_carbon_delta <- carbon_benefit_curve %>% 
  summarize(max_v = max(v),
            current_mpas_v = if_else(protection_levels$f_eez_highly_mpas <= 0, 0, 
                                     max(v[fraction_protected <= protection_levels$f_eez_highly_mpas])),
            max_delta_v = max_v - current_mpas_v,
            ninety_percent_delta_v = current_mpas_v + 0.9*max_delta_v,
            optim_protection = 100*max(fraction_protected[v == max_v]),
            optim_protection_90 = 100*max(fraction_protected[which.min(abs(ninety_percent_delta_v - v))])) %>% 
   mutate_at(vars(optim_protection_90, optim_protection), round, 2))
```

```{r, warning = F}
carbon_raster <- carbon_ranking %>% 
  rasterize_ranking() 

map_priorities(rank_raster = carbon_raster, 
               priority = "carbon", 
               scenario = country_name,
               projection = local_crs, 
               mpas_shp = highly_mpas,
               land_shp = land_shp) +
  ggsave(filename = file.path(country_name, "carbon_map.png"), height = 7, width = 7)
```
```{r}
carbon_summary <- carbon_benefit_curve %>% 
  mutate(v = scales::rescale(v)) %>% 
  ungroup() %>% 
  summarize(objective = "carbon",
            max_v = max(v)*total_co2_in_eez,
            optim_protection = fraction_protected[which.min(abs(v - max(v)))],
            v_at_10_percent = v[which.min(abs(fraction_protected - 0.1))],
            v_at_30_percent = v[which.min(abs(fraction_protected - 0.3))])
```
## Food

```{r}
food_benefit_curve <- get_benefit_curve(goal = "food", rank_df = food_ranking)

plot_curve(curve_df = food_benefit_curve, goal = "food", country_name = country_name)+
  theme(plot.title.position = "plot")+
  ggsave(filename = file.path(country_name, "food_curve.png"), height = 5, width = 7)

(max_food_delta <- food_benefit_curve %>% 
  summarize(max_v = max(v),
            current_mpas_v = if_else(protection_levels$f_eez_highly_mpas <= 0, 0, 
                                     max(v[fraction_protected <= protection_levels$f_eez_highly_mpas])),
            max_delta_v = max_v - current_mpas_v,
            ninety_percent_delta_v = current_mpas_v + 0.9*max_delta_v,
            optim_protection = 100*max(fraction_protected[v == max_v]),
            optim_protection_90 = 100*max(fraction_protected[which.min(abs(ninety_percent_delta_v - v))])) %>% 
   mutate_at(vars(optim_protection_90, optim_protection), round, 2))
```
```{r, warning = F}
food_raster <- food_ranking %>% 
  rasterize_ranking() 

map_priorities(rank_raster = food_raster, 
               priority = "food", 
               scenario = "mixed model",
               projection = local_crs, 
               mpas_shp = highly_mpas,
               land_shp = land_shp) +
      ggsave(filename = file.path(country_name, "food_map.png"), height = 7, width = 7)

```

```{r}
food_summary <- food_benefit_curve %>% 
  mutate(v = scales::rescale(v)) %>% 
  ungroup() %>% 
  summarize(objective = "food",
            max_v = max(v)*max_food_delta$max_delta_v,
            optim_protection = fraction_protected[which.min(abs(v - max(v)))],
            v_at_10_percent = v[which.min(abs(fraction_protected - 0.1))],
            v_at_30_percent = v[which.min(abs(fraction_protected - 0.3))])
```


```{r}
bind_rows(food_summary, 
          carbon_summary, 
          bio_summary) %>% 
  write_csv(file.path(country_name, "summary_results.csv"))
```

# Triple wins

```{r}
raster_stack  <- stack(bio_raster, carbon_raster, food_raster)

raster_stack <- raster_stack[[c(1,3,5, 6)]]

names(raster_stack) <- c("bio","carbon","food", "f_highly_mpa")

top_p <- 0.7

triple_wins <- overlay(raster_stack, 
        unstack = TRUE,
        fun = function(x, y, z, m){
          ifelse(m > 0, 4,
                 ifelse(x >= top_p & y >= top_p & z >= top_p, 3,
                        ifelse( (x >= top_p & y >= top_p) | (x >= top_p & z >= top_p) | (z >= top_p & y >= top_p), 2,
                                ifelse(x >= top_p | y >= top_p | z >= top_p, 1, NA))))}) %>% 
  projectRaster(eez_raster, method = "ngb")
  
triple_wins_df <- stack(triple_wins, eez_raster) %>% 
  projectRaster(crs = local_crs, method = c("ngb"), over = T) %>% 
  crop(as_Spatial(st_transform(eez, local_crs))) %>% 
  mask(as_Spatial(st_transform(eez, local_crs))) %>% 
  as.data.frame(xy = T) %>% 
  set_names(c("lon", "lat", "n_wins", "f_eez")) %>%
  filter(!is.na(n_wins), n_wins > 0)

triple_wins_df %>% 
  ggplot(aes(x = lon, y = lat))+
  geom_raster(aes(fill = as.factor(n_wins)), alpha = 1)+
  geom_sf(data =  st_transform(land_shp, crs = local_crs), 
          inherit.aes = F, fill = "gray", col = "transparent",linetype = 2, size = 0.5)+
  scale_fill_manual(values  = c("#f5ee9e", "#f49e4c", "#ab3428", "lightblue"),
                    labels = c("1", "2", "3", "MPAs"),
                    guide = guide_legend(
                      title = "Number of goals ",
                      title.position = 'top',
                      direction = "horizontal",
                      keyheight = unit(1.5, units = "mm"),
                      keywidth = unit(0.5, units = "cm"),
                      title.hjust = 0.5,
                      label.hjust = 0.5,
                      nrow = 1,
                      reverse = T,
                      label.position = "top"))+
  easyR::ggtheme_map()+
  labs(title = "Overlap of top 30% priority areas", subtitle = country_name)+
  ggsave(filename = file.path(country_name, "overlap.png"), height = 7, width = 7)
```

```{r}
unprotected_eez_size <- protection_levels$eez_size - sum(triple_wins_df$f_eez[triple_wins_df$n_wins == 4])
          
100*sum(triple_wins_df$f_eez[triple_wins_df$n_wins == 3])/unprotected_eez_size

100*sum(triple_wins_df$f_eez[triple_wins_df$n_wins == 2])/unprotected_eez_size
```

# Equal weights 

```{r}
equal_wts_w_vector <- calculate_multiobjective_weights(alpha_b = 1/3, alpha_c = 1/3, alpha_f = 1/3,
                                                       b_wts = bio_weights, c_wts = carbon_weights, f_wts = food_weights, 
                                                       max_b = max_bio_delta$max_delta_v, max_c = max_carbon_delta$max_delta_v, 
                                                       max_f_a1  =  max_food_delta$max_delta_v, max_f_a2  =  max_food_delta$max_delta_v,
                                                       effort_assumption = 2)

equal_wts_ranking <- run_prioritization(unprotected_matrix, 
                                        step_size = 1,
                                        wts = equal_wts_w_vector)

rank_complete<- ocean_df %>%
  filter(f_eez > 0) %>%
  left_join(equal_wts_ranking) %>%
  replace(is.na(.), 0) %>%
  arrange(pick_order) %>%
  left_join(norm_features_df) %>%
  replace(is.na(.), 0)

protection_accumulation <- rank_complete %>%
  transmute(lon,lat, cell_id, f_highly_mpa,
            fraction_eez = if_else(f_highly_mpa > 0, f_highly_mpa, f_eez),
            fraction_protected = cumsum(fraction_eez)/protection_levels$eez_size) %>%
  select(-fraction_eez)

bio_benefit_accumulation <- rank_complete %>%
      select(all_of(bio_feature_names)) %>%
      mutate_all(.funs = cumsum) %>%
      sweep(MARGIN = 2, bio_remains_BAU, `+`) %>%
      mutate_all(.funs = ~(.)^z_bio) %>%
      as.matrix() %*% as.matrix(equal_wts_w_vector[bio_feature_names]) %>%
      as_tibble() %>%
      set_names("v") %>% 
  mutate(fraction_protected = protection_accumulation$fraction_protected)

food_benefit_accumulation <- rank_complete %>%
      select(all_of(stock_names)) %>%
      mutate_all(.funs = cumsum) %>%
      apply(MARGIN = 1,
            FUN = estimate_delta_catch,
            e = stocks_info$ex_rate, m = stocks_info$m, r = stocks_info$r, k = stocks_info$k, effort_assumption = 2) %>%
      t() %>%
      as.matrix() %*% as.matrix(equal_wts_w_vector[stock_names]) %>%
      as_tibble() %>%
      rowSums() %>%
      enframe(name = NULL) %>%
      set_names("v") %>% 
    mutate(fraction_protected = protection_accumulation$fraction_protected)

carbon_benefit_accumulation <- rank_complete %>%
      select(carbon) %>%
      mutate_all(.funs = cumsum) %>%
      sweep(MARGIN = 2, carbon_remains_BAU, `+`) %>%
      rowSums() %>%
      enframe(name = NULL) %>%
      set_names("v") %>% 
    mutate(fraction_protected = protection_accumulation$fraction_protected,
           v = v*equal_wts_w_vector["carbon"])
```

Optimal protectin levels

```{r}
equal_wts_curves <- tibble(goal = c("food", "carbon", "biodiversity"),
                         benefit_curve = list(food_benefit_accumulation, carbon_benefit_accumulation, bio_benefit_accumulation))
  
equal_wts_combined_curve <- equal_wts_curves %>% 
  group_by(goal) %>% 
  summarise(bind_rows(benefit_curve)) %>% 
  group_by(fraction_protected) %>% 
  summarize(v = sum(v)) 

opt_equal_wts_protection <- equal_wts_combined_curve %>% 
  slice(which.max(v)) %>% 
  pull(fraction_protected)

equal_wts_results_df <- equal_wts_curves %>% 
  group_by(goal) %>% 
  summarise(bind_rows(benefit_curve)) %>% 
  mutate(v = if_else(goal == "food", v/max_food_delta$max_delta_v, scales::rescale(v)))

equal_wts_results_df %>% 
  filter(fraction_protected == opt_equal_wts_protection) %>% 
  write_csv(file.path(country_name, "optimal_protection_equal_wts.csv"))
```

```{r}
equal_wts_combined_curve %>% 
  ggplot()+
  geom_line(aes(fraction_protected, v))
```

```{r}
equal_wts_results_df %>% 
  ggplot()+
  geom_line(aes(fraction_protected, v, col = goal))+
  theme_minimal()+
  theme_classic()+
  ylim(0, NA)+
  scale_x_continuous(breaks = c(0,.2,.4,.6,.8,1))+
  geom_rect(aes(xmin = 0,
                xmax = protection_levels$f_eez_highly_mpas,
                ymin = 0,
                ymax = max(v)),
            fill = "lightblue", alpha = 0.5)+
  labs(x = "Fraction EEZ Protected",
       y = "Normalized Benefits",
       title = "Co-Benefits: equal-weight multiobjective prioritization",
       subtitle = country_name)+
  easyR::ggtheme_plot()+
  scale_color_viridis_d()+
  ggsave(filename = file.path(country_name, "equal_wts_benefit_curves.png"),
         width = 8, height = 5)
```

What about in the top 30%?

```{r}
equal_wts_results_df %>% 
  group_by(goal) %>% 
  slice(which.min(abs(fraction_protected - 0.3)))
```

```{r, warning = F}
multi_raster <- equal_wts_ranking %>% 
  rasterize_ranking() 

map_priorities(rank_raster = multi_raster, 
               priority = "Equal wieghts", 
               scenario = country_name,
               projection = local_crs, 
               mpas_shp = highly_mpas,
               land_shp = land_shp) +
        ggsave(filename = file.path(country_name, "equal_wts_map.png"), height = 7, width = 7)
```
