---
title: "National priorities"
author: "*Compiled on `r date()` by `r Sys.info()['user']`*"
output: 
  html_document:
    code_folding: show
    toc: true
    toc_depth: 1
    toc_float: yes
    number_sections: false
    theme: cerulean
    highlight: haddock
---


```{r}
library(raster)
library(sf)
library(tidyverse)

options(scipen = 999)
```

# Load data

```{r}
emlab_data_dir <- "~/Google Drive/Shared drives/emlab/data"

gocp_project_dir <- "~/Google Drive/Shared drives/emlab/projects/current-projects/ocean-conservation-priorities"

source(file.path(emlab_data_dir, "ocean-conservation-priorities","functions", "food_provision_foos.R"))

load(file.path(emlab_data_dir, "ocean-conservation-priorities","inputs", "national_analyses","common_inputs.RData"))

ocean_low_res_moll <- raster::raster(file.path(emlab_data_dir, "ocean-conservation-priorities", "inputs", "ocean_low_res_moll.tif"))
```

## EEZ

```{r}
world_eezs <- sf::st_read(file.path(emlab_data_dir, "marine-regions-eez-v11", "World_EEZ_v11_20191118_gpkg", "eez_v11.gpkg")) %>%
  sf::st_wrap_dateline(options = c("WRAPDATELINE=YES", "DATELINEOFFSET=180"), quiet = TRUE) %>%
  janitor::clean_names()

world_eezs_info <- world_eezs %>%
  st_drop_geometry()

EU_terris <- c("Belgium", "Bulgaria", "Croatia", "Cyprus", "Denmark", "Estonia", "Finland", "France", "Germany", "Greece", "Ireland", "Italy", "Latvia", "Lithuania",  "Malta", "Netherlands", "Poland", "Portugal", "Romania", "Slovakia", "Slovenia", "Spain", "Sweden")

uk_eez <- world_eezs %>% 
  filter(pol_type %in% c("200NM", "200 NM")) %>% 
  filter(territory1 %in% EU_terris) %>% 
  st_transform(crs = crs(ocean_low_res_moll)) %>% 
  st_simplify(dTolerance = 1000, preserveTopology = T)

uk_eez %>% st_drop_geometry()

uk_eez_raster <- uk_eez %>% 
  rasterize(ocean_low_res_moll, field = 1)

plot(uk_eez_raster)
```

## Ocean df

```{r}
eez_df <- stack(ocean_low_res_moll, uk_eez_raster) %>% 
  raster::as.data.frame(xy = T) %>% 
  set_names(c("lon", "lat", "ocean","f_eez")) %>% 
  filter(!is.na(ocean)) %>% 
  rowid_to_column(var = "cell_id") %>% 
  as_tibble() %>% 
  filter(!is.na(f_eez))

ocean_df <- ocean_df %>% 
  left_join(eez_df)

(protection_levels <- ocean_df %>% 
  summarise(f_highly_mpas = sum(f_highly_mpa/n()),
            eez_size = sum(f_eez, na.rm = T),
            f_eez_highly_mpas = sum(f_highly_mpa[f_eez > 0]/eez_size, na.rm = T)) %>% 
  mutate_if(is.numeric, round, 4) )

eez_cell_ids <- ocean_df$cell_id[ocean_df$f_eez > 0]
```

# Ranking

## Initial conditions

```{r}
z_bio <-  0.25

is_mpa_vect <- ocean_df$f_highly_mpa > 0

protected_cells <- matrix(is_mpa_vect, nrow = 1, ncol = nrow(norm_features_matrix))

unprotected_matrix <- norm_features_matrix[!protected_cells, ]

protected_matrix <- norm_features_matrix[protected_cells, ]

baseline_state <- protected_cells%*%norm_features_matrix

baseline_state[,"carbon"] <- baseline_state[, "carbon"] + carbon_remains_BAU

baseline_state[, bio_feature_names] <- baseline_state[, bio_feature_names] + bio_remains_BAU

max_slopes_bio <- z_bio*baseline_state[, bio_feature_names]^(z_bio - 1)

max_slope_carbon <- 1

names(max_slope_carbon) <- "carbon"
```

## Limiting ranking to ROI

```{r}
unprotected_matrix <- unprotected_matrix[rownames(unprotected_matrix) %in% eez_cell_ids,] ## Algorithm can only choose from within EEZ. 
```

## Run algorithm

```{r}
calculate_multiobjective_weights <- function(alpha_b, alpha_c, alpha_f, 
                                             b_wts, c_wts, f_wts, 
                                             max_b, max_c, max_f_a1, max_f_a2, 
                                             effort_assumption){
  
  if(all(c(alpha_b, alpha_c, alpha_f) >= 0) & alpha_b + alpha_c + alpha_f != 1) stop("weights don't add up to 1")
  
  if(effort_assumption == 1){
    max_f <- max_f_a1
  } 
  else if (effort_assumption == 2){
    max_f <- max_f_a2
  }
  
  bio_w <- alpha_b*b_wts*max_f/max_b
  
  carbon_w <- alpha_c*c_wts*max_f/max_c
  
  food_w <- alpha_f*f_wts
  
  feature_weigths <- c(bio_w, carbon_w, food_w)
  
  return(feature_weigths)
  
}
```

```{r}
estimate_multiobjective_slopes <- function(x, feature_group, feature_wts, max_slopes_b, max_slopes_c,
                                           z_bio = 0.25, z_carbon = 1, effort_assumption,  e, m, k, r){

  slopes <- vector(mode = "numeric", length = length(feature_group))

  slopes[feature_group == 1] <- pmin(max_slopes_b, z_bio*x[feature_group == 1]^(z_bio - 1))

  slopes[feature_group == 2] <- pmin(max_slopes_c, z_carbon*x[feature_group == 2]^(z_carbon - 1))

  slopes[feature_group == 3] <- estimate_catch_slopes(k_protected = x[feature_group == 3],
                                                      effort_assumption = effort_assumption,
                                                      e = e,
                                                      m = m,
                                                      k = k,
                                                      r = r)

  weighted_slopes <- slopes*feature_wts

  return(weighted_slopes)

}
```

```{r}
run_prioritization <- function(unprotected_matrix, wts, step_size){
  
  ranking <- list()
  
  current_pick <- 0
  
  current_state <- baseline_state
  
  while(nrow(unprotected_matrix) > 0){
    
    current_pick <- sum(current_pick, 1)
    
    slopes <- estimate_multiobjective_slopes(x = current_state, feature_group = group_ids, feature_wts  = wts,
                                             max_slopes_b = max_slopes_bio, max_slopes_c = max_slope_carbon, 
                                             e = stocks_info$ex_rate, m = stocks_info$m, k = stocks_info$k, 
                                             r = stocks_info$r, effort_assumption = 2)
    
    delta <- unprotected_matrix%*%as.matrix(slopes)
    
    best_cell_indeces <- doBy::which.maxn(delta, n = step_size)
    
    best_cells <- delta[best_cell_indeces,] %>%
      enframe() %>%
      set_names(c('cell_id', "delta")) %>%
      mutate(pick_order = current_pick)
    
    ranking <- bind_rows(ranking, best_cells)
    
    current_state <- unprotected_matrix[best_cell_indeces, ,drop = F] %>%
      colSums() +
      current_state
    
    unprotected_matrix <- unprotected_matrix[-best_cell_indeces, , drop = F]
  }
  
  ranking$cell_id <- as.integer(ranking$cell_id)
  
  return(ranking)
  
}
```

```{r}
food_ranking <- run_prioritization(unprotected_matrix, 
                                   step_size = 10,
                                   wts = calculate_multiobjective_weights(alpha_b = 0, alpha_c = 0, alpha_f = 1,
                                                                          b_wts = bio_weights, c_wts = carbon_weights,
                                                                          f_wts = food_weights, max_b = 1, max_c = 1, 
                                                                          max_f_a1  = 1, max_f_a2  = 1, effort_assumption = 2))
```


# Results

```{r}
norm_features_df <- norm_features_matrix %>%
  as_tibble(rownames = NA) %>%
  rownames_to_column("cell_id") 

norm_features_df$cell_id <- as.integer(norm_features_df$cell_id)

rank_complete<- ocean_df %>% 
    filter(f_eez > 0) %>% 
    left_join(food_ranking) %>% 
    replace(is.na(.), 0) %>% 
    arrange(pick_order) %>% 
    left_join(norm_features_df) %>%
    replace(is.na(.), 0) 

protection_accumulation <- rank_complete %>% 
    transmute(lon,lat, cell_id, f_highly_mpa, 
              fraction_eez = if_else(f_highly_mpa > 0, f_highly_mpa, f_eez),
              fraction_protected = cumsum(fraction_eez)/protection_levels$eez_size) %>% 
    select(-fraction_eez)

benefit_accumulation <- rank_complete %>% 
      select(all_of(stock_names)) %>%
      mutate_all(.funs = cumsum) %>% 
      apply(MARGIN = 1, 
            FUN = estimate_delta_catch, 
            e = stocks_info$ex_rate, m = stocks_info$m, r = stocks_info$r, k = stocks_info$k, effort_assumption = 2) %>%
      t() %>%
      as.matrix() %*% as.matrix(food_weights)  %>%
      as_tibble() %>%
      rowSums() %>%
      enframe(name = NULL) %>%
      set_names("v")

benefit_curve <- bind_cols(protection_accumulation, benefit_accumulation)

max_food_delta <- benefit_curve %>% 
  summarize(max_catch = max(v))

benefit_curve %>% 
      mutate(v = v/10^6) %>% 
      ggplot()+
      geom_line(aes(fraction_protected, v))+
      labs(x = "Fraction EEZ Protected",
           y = "Change in Global Catch (Million tons)",
           title = "Contribution to global catch")
```

```{r}
benefit_curve %>% slice(which.max(v))

benefit_curve %>% slice(which.min(abs(fraction_protected - 0.1)))

benefit_curve %>% slice(which.min(abs(fraction_protected - 0.3)))
```

```{r}
rank_raster <- ocean_df %>% 
    filter(f_eez > 0) %>% 
    left_join(food_ranking) %>%
    replace(is.na(.), 0) %>% 
    arrange(pick_order) %>% 
    mutate(rank = 1 - scales::rescale(base::rank(pick_order, ties.method = "first", na.last = F)),) %>% 
    select(lon, lat, rank, f_highly_mpa) %>% 
    rasterFromXYZ(crs = crs(ocean_low_res_moll))

plot(rank_raster)
```

